### ISSUE TITLE
Question to Program AsymmetricEncryption

### ISSUE THREAD

**Issue by EdAdvokat** [SchneiderInfosystems/WinRTCrypto#1]
During the program test of AsymmetricEncryption with the algorithm ECDSAP246Sha256 I had to realize that
and verification was possible, but the Encrypt button was grayed out and therefore encryption was not possible in this setting.
encryption was not possible in this setting.
Am I doing something wrong or is there another explanation? 
I am an interested Delphi fan, but not a professional.

**Comment by SchneiderInfosystems** [comment]
ECDSA is not intended for encrypting messages, but specifically for signing and verification. This is because the mathematical operations and objectives behind signing and encryption are fundamentally different.
For more information about the purpose of ECDSA read this document in chapter 1.1 and 1.2:
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186.pdf?form=MG0AV3
BTW. If you override the disabling of the button encrypt at line 142 and remove 
`and (cboAlgo.ItemIndex < 5)`
you will get an OLE Exception 'Not implemented'. Therefore, I have grayed out the Encrypt button for this algorithm.

I wish you continued success in exploring this wrapper library, and if you like it, please give it a star.

**Comment by EdAdvokat** [comment]
In the meantime I have tested the program AsymmetricEncryption and also HybridEncryption under real conditions. encrypt/decrypt worked without errors with HybridEncryption, although I received the following warning: ShowWarning( 'Failed: Resulting clear text different than starting clear text');
However, the decrypted text corresponded to the sender's original. The test under real conditions with the program AsymmetricEncryption, on the other hand, failed during decryption with the error message (line 358):Assert(lblResult.Caption = 'Chiffre', 'Decryption needs chiffre');
After I commented out this line, this program also worked without errors. Of course I encrypted the message with the public key of the recipient in both cases, but did I do something wrong or overlooked something so that the error message (line 358) appears and decryption was not possible? 
thank you again for your efforts.

**Comment by SchneiderInfosystems** [comment]
If you see the failed message: Resulting "clear text different than starting clear text" than you should check the time within the predefined clear text message. Typically, after restart the application you get another time in the clear text for testing.

After inspecting the code related to your message with the assert in AysmmetricEncryptionFrm in Line 358, 
I found a workflow wich could explain your test:
1. Create key pair and press Save Keys
2. Encrpyt and press Save Chiffre.
3. Restart the application 
4. Reload the keys and chiffre text
5. Press decrypt

Was this your workflow? Can you test the newest version?
Now I have added to save/load pairs for encrypt and sign.

Are you interested in a short training course where I can expain all the details you need to know? 
If so, contact me at delphi @ schneider-infosys.ch.

**Comment by EdAdvokat** [comment]
I still have a question about the SymmetricEncryption program and I don't want to be a pain.
In the literature (Cryptography by Klaus Schmeh 2016), a key length of 16 characters per 1 byte (8 times 16 equals 128bit) is described for AES 128bit, 24 characters for 192bit 
and 32 characters for AES 256bit bit. This is also how I know it when using AES from DEC. There I enter 16 characters as the key for the 128 bit key length 
and encrypt a plain text with it.
Here in the SymmetricEncryption program, however, 24 characters are required or generated for the 128-bit encryption (32 characters for 192 and 44 characters for 256-bit).
Debug has given line 314 SelectKeySizeinBytes a result of 16, so only 16 characters should be used. However, there are 24 characters.
Why is this the case in this program?

**Comment by SchneiderInfosystems** [comment]
Your theory is completely correct. But please don't talk about characters here, but about bytes.

But what you are not taking into account is the coding of the bytes. I use Base64 notation and not hexadecimal to display the keys, the IV and the cipher. Of course you don't have to do it this way, but it's the best way to keep data readable for humans but as short as possible. With hex, we have 2 characters for one byte. With Base64 we have 3 characters for 4 bytes. The rest is simple math. BTW, that is why I show always the key length in bits in the sample application.

I'm still convinced that a short training session would help you a lot and give you the confidence you need to build your own application. It would also help you to handle the keys, IV and cipher correctly and not make mistakes. These examples were part of a training session at EKON 27. I hope you can understand that I can't offer a training for free. 

Please note that I can no longer answers such questions in this forum, which is open for reporting bugs only.
